replicaCount: 1
# image:
#   repository: lumszy/python-flask-app
#   pullPolicy: IfNotPresent
#   tag: "f76381"
image:
  repository: lumszy/${{ values.app-name }} #python-flask-app
  pullPolicy: IfNotPresent
  tag: ${{ values.app_name }}-${{ values.app_env }}-latest #"f76381"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: ${{ values.app_name }}-${{ values.app_env }}.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  requests:
    cpu: 5m
    memory: 10M
  limits:
    cpu: 50m
    memory: 50M
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
